// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8yRNywxX1HVLe9dpos1UNKPfBaHD7BM',
    appId: '1:486246775823:web:ff1a1b4468ba0e313fb77a',
    messagingSenderId: '486246775823',
    projectId: 'redeem-code-admin-47c30',
    authDomain: 'redeem-code-admin-47c30.firebaseapp.com',
    storageBucket: 'redeem-code-admin-47c30.appspot.com',
    measurementId: 'G-BFCBCJMMP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqflEIP-4xoR7TQA2I2NuVTChhvzjD0q4',
    appId: '1:486246775823:android:82a5da165164cfa43fb77a',
    messagingSenderId: '486246775823',
    projectId: 'redeem-code-admin-47c30',
    storageBucket: 'redeem-code-admin-47c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSb777ql0AzbuxJL7uuu1pTwe1vyPSh0',
    appId: '1:486246775823:ios:d8323a603b3cc1e83fb77a',
    messagingSenderId: '486246775823',
    projectId: 'redeem-code-admin-47c30',
    storageBucket: 'redeem-code-admin-47c30.appspot.com',
    iosClientId:
        '486246775823-b4s9v0pa4f0hdln6aq8cb9ogr0b3j6fo.apps.googleusercontent.com',
    iosBundleId: 'com.syakirarif.genshinCharacters',
  );
}
